# Generated by Django 3.0.4 on 2020-04-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaa', models.CharField(max_length=200)),
                ('bbb', models.CharField(max_length=200)),
                ('flagcalc', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
