# Generated by Django 3.0.4 on 2020-04-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='flagcalc',
            field=models.BooleanField(default=True),
        ),
    ]
